### ISSUE TITLE
about footer's background color

### ISSUE THREAD

**Issue by TCPsoftware** [AmazingApps/AmazingApps.github.io#14] opened 2018-02-22 12:22 UTC
Could you change a background color for <a href="http://amazingapps.org/index.html#three">get in touch</a> and <a href="http://amazingapps.org/index.html#footer">footer</a>?
Maybe it looks ugly and not intuitive now.

**Comment by Riajyuu** [comment] 2018-02-22 12:38
Em
That's interesting.
What color do you suggest since I think it looks more universal in designing language now.

**Comment by TCPsoftware** [comment] 2018-02-23 03:42
Maybe a deep color ?
or a background image will also be suitable.
Then the module will be more intuitive.

**Comment by TCPsoftware** [comment] 2018-02-23 03:56
and more probably to let others get in touch with your organization

**Comment by Riajyuu** [comment] 2018-02-23 04:01
That's interesting.
You may join our telegram group for further discussion via the given invitation links.
That's for your time.

**Comment by TCPsoftware** [comment] 2018-02-23 04:07
sorry but i could not launch telegram because of China's Great Firewall

**Comment by gloomy-ghost** [comment] 2018-05-15 08:09
It's just a form of minimalism design, closing as intended behaviour.

**Closed as completed by gloomy-ghost** 2018-05-15 08:09 UTC
